-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

module AbsCpp where

newtype Id = Id String
  deriving (Eq, Ord, Show, Read)

data Program = PDefs [Def]
  deriving (Eq, Ord, Show, Read)

data Def = DFun Type Id [Arg] [Stm]
  deriving (Eq, Ord, Show, Read)

data Arg = ADecl Type Id
  deriving (Eq, Ord, Show, Read)

data Stm
    = SExp Exp
    | SDecls Type [Id]
    | SInit Type Id Exp
    | SReturn Exp
    | SReturnVoid
    | SWhile Exp Stm
    | SBlock [Stm]
    | SIf Exp Stm
    | SIfElse Exp Stm Stm
    | SFunc Mem [Exp]
  deriving (Eq, Ord, Show, Read)

data Mem = MId Id | MCall Mem Mem
  deriving (Eq, Ord, Show, Read)

data Type
    = TId Id
    | TIds Id Id
    | TBrac Type Type
    | TAlias Type
    | TNs Type Type
  deriving (Eq, Ord, Show, Read)

data Exp
    = EFunc Mem [Exp]
    | EIf Exp Exp Exp
    | ETrue
    | EFalse
    | EInt Integer
    | EDouble Double
    | EString String
    | EId Id
    | ENs Id Id
    | EArray Id Exp
    | EApp Id [Exp]
    | ECout Exp [Exp]
    | EPIncr Exp
    | EPDecr Exp
    | ECin Exp Exp
    | EIncr Exp
    | EDecr Exp
    | ETimes Exp Exp
    | EDiv Exp Exp
    | EMod Exp Exp
    | EPlus Exp Exp
    | EMinus Exp Exp
    | ELt Exp Exp
    | EGt Exp Exp
    | ELtEq Exp Exp
    | EGtEq Exp Exp
    | EEq Exp Exp
    | ENEq Exp Exp
    | EAnd Exp Exp
    | EOr Exp Exp
    | EAss Exp Exp
    | ETyped Exp Type
  deriving (Eq, Ord, Show, Read)

